disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - trailing_whitespace
  - todo
  - implicit_getter
  - legacy_constructor
  - empty_enum_arguments
  - empty_parentheses_with_trailing_closure
  - multiple_closures_with_trailing_closure
  - valid_ibinspectable
  - cyclomatic_complexity
opt_in_rules: # some rules are only opt-in
  - empty_count
  # swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

todo: warning
identifier_name:
  min_length: 2
line_length:
  - 260 # warning
  - 350 # error
function_parameter_count:
  - 6
large_tuple:
  - 3
  - 5
function_body_length:
  - 50
  - 100
